spring.datasource.url=jdbc:h2:file:./data/jwtapp-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


app.jwt.secret=jljIU)0jsfn2349jknnj()NRW#Cg7t87s,dasldakd;lkslkl;k9u8rsafacs3gygvefryt63s1acsdcc

